import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import '../../objectbox.g.dart'; // This will be generated by build_runner

class ObjectBoxService {
  late final Store store;

  ObjectBoxService._create(this.store);

  /// Create an instance of ObjectBoxService to use throughout the app.
  static Future<ObjectBoxService> create() async {
    final docsDir = await getApplicationDocumentsDirectory();
    // Open the store in the documents directory (or dynamic depending on platform)
    final storePath = p.join(docsDir.path, "gym-app-db");
    
    // Check if store is already open or open it
    final store = await openStore(directory: storePath);
    return ObjectBoxService._create(store);
  }
}
