// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/history/data/models/workout_session_entity.dart';
import 'features/workout/data/models/workout_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6879480637049847989),
    name: 'ExerciseEntity',
    lastPropertyId: const obx_int.IdUid(7, 1464783182992380359),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 231256136036700834),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6750499716414085536),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5566363948405836744),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1556160682526217980),
        name: 'sets',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3859088017587302107),
        name: 'reps',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7169566214768779338),
        name: 'defaultWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1464783182992380359),
        name: 'programId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3434331380561699962),
        relationField: 'program',
        relationTarget: 'WorkoutProgramEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8992228114827215693),
    name: 'WorkoutProgramEntity',
    lastPropertyId: const obx_int.IdUid(5, 5343697026691882084),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1788873643091369422),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6531597401178793531),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2344989997266328974),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7339114637262735169),
        name: 'level',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5343697026691882084),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'exercises',
        srcEntity: 'ExerciseEntity',
        srcField: 'program',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1202436229571076132),
    name: 'WorkoutSessionEntity',
    lastPropertyId: const obx_int.IdUid(5, 8496532033844004934),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5859174407862279108),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3127719081036296037),
        name: 'programName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5928465971021259044),
        name: 'dateTimestamp',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1482796845441125706),
        name: 'durationMinutes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8496532033844004934),
        name: 'exercisesJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1202436229571076132),
    lastIndexId: const obx_int.IdUid(1, 3434331380561699962),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ExerciseEntity: obx_int.EntityDefinition<ExerciseEntity>(
      model: _entities[0],
      toOneRelations: (ExerciseEntity object) => [object.program],
      toManyRelations: (ExerciseEntity object) => {},
      getId: (ExerciseEntity object) => object.id,
      setId: (ExerciseEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ExerciseEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final categoryOffset = fbb.writeString(object.category);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addInt64(3, object.sets);
        fbb.addInt64(4, object.reps);
        fbb.addFloat64(5, object.defaultWeight);
        fbb.addInt64(6, object.program.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final setsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final repsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final defaultWeightParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = ExerciseEntity(
          id: idParam,
          name: nameParam,
          category: categoryParam,
          sets: setsParam,
          reps: repsParam,
          defaultWeight: defaultWeightParam,
        );
        object.program.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.program.attach(store);
        return object;
      },
    ),
    WorkoutProgramEntity: obx_int.EntityDefinition<WorkoutProgramEntity>(
      model: _entities[1],
      toOneRelations: (WorkoutProgramEntity object) => [],
      toManyRelations: (WorkoutProgramEntity object) => {
        obx_int.RelInfo<ExerciseEntity>.toOneBacklink(
          7,
          object.id,
          (ExerciseEntity srcObject) => srcObject.program,
        ): object.exercises,
      },
      getId: (WorkoutProgramEntity object) => object.id,
      setId: (WorkoutProgramEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WorkoutProgramEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final levelOffset = fbb.writeString(object.level);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, levelOffset);
        fbb.addInt64(4, object.durationMinutes);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final levelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final object = WorkoutProgramEntity(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          level: levelParam,
          durationMinutes: durationMinutesParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<WorkoutProgramEntity>(
          object.exercises,
          store,
          obx_int.RelInfo<ExerciseEntity>.toOneBacklink(
            7,
            object.id,
            (ExerciseEntity srcObject) => srcObject.program,
          ),
        );
        return object;
      },
    ),
    WorkoutSessionEntity: obx_int.EntityDefinition<WorkoutSessionEntity>(
      model: _entities[2],
      toOneRelations: (WorkoutSessionEntity object) => [],
      toManyRelations: (WorkoutSessionEntity object) => {},
      getId: (WorkoutSessionEntity object) => object.id,
      setId: (WorkoutSessionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (WorkoutSessionEntity object, fb.Builder fbb) {
        final programNameOffset = fbb.writeString(object.programName);
        final exercisesJsonOffset = fbb.writeString(object.exercisesJson);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, programNameOffset);
        fbb.addInt64(2, object.dateTimestamp);
        fbb.addInt64(3, object.durationMinutes);
        fbb.addOffset(4, exercisesJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final programNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final dateTimestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final durationMinutesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final exercisesJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = WorkoutSessionEntity(
          id: idParam,
          programName: programNameParam,
          dateTimestamp: dateTimestampParam,
          durationMinutes: durationMinutesParam,
          exercisesJson: exercisesJsonParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ExerciseEntity] entity fields to define ObjectBox queries.
class ExerciseEntity_ {
  /// See [ExerciseEntity.id].
  static final id = obx.QueryIntegerProperty<ExerciseEntity>(
    _entities[0].properties[0],
  );

  /// See [ExerciseEntity.name].
  static final name = obx.QueryStringProperty<ExerciseEntity>(
    _entities[0].properties[1],
  );

  /// See [ExerciseEntity.category].
  static final category = obx.QueryStringProperty<ExerciseEntity>(
    _entities[0].properties[2],
  );

  /// See [ExerciseEntity.sets].
  static final sets = obx.QueryIntegerProperty<ExerciseEntity>(
    _entities[0].properties[3],
  );

  /// See [ExerciseEntity.reps].
  static final reps = obx.QueryIntegerProperty<ExerciseEntity>(
    _entities[0].properties[4],
  );

  /// See [ExerciseEntity.defaultWeight].
  static final defaultWeight = obx.QueryDoubleProperty<ExerciseEntity>(
    _entities[0].properties[5],
  );

  /// See [ExerciseEntity.program].
  static final program =
      obx.QueryRelationToOne<ExerciseEntity, WorkoutProgramEntity>(
        _entities[0].properties[6],
      );
}

/// [WorkoutProgramEntity] entity fields to define ObjectBox queries.
class WorkoutProgramEntity_ {
  /// See [WorkoutProgramEntity.id].
  static final id = obx.QueryIntegerProperty<WorkoutProgramEntity>(
    _entities[1].properties[0],
  );

  /// See [WorkoutProgramEntity.name].
  static final name = obx.QueryStringProperty<WorkoutProgramEntity>(
    _entities[1].properties[1],
  );

  /// See [WorkoutProgramEntity.description].
  static final description = obx.QueryStringProperty<WorkoutProgramEntity>(
    _entities[1].properties[2],
  );

  /// See [WorkoutProgramEntity.level].
  static final level = obx.QueryStringProperty<WorkoutProgramEntity>(
    _entities[1].properties[3],
  );

  /// See [WorkoutProgramEntity.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<WorkoutProgramEntity>(
    _entities[1].properties[4],
  );

  /// see [WorkoutProgramEntity.exercises]
  static final exercises =
      obx.QueryBacklinkToMany<ExerciseEntity, WorkoutProgramEntity>(
        ExerciseEntity_.program,
      );
}

/// [WorkoutSessionEntity] entity fields to define ObjectBox queries.
class WorkoutSessionEntity_ {
  /// See [WorkoutSessionEntity.id].
  static final id = obx.QueryIntegerProperty<WorkoutSessionEntity>(
    _entities[2].properties[0],
  );

  /// See [WorkoutSessionEntity.programName].
  static final programName = obx.QueryStringProperty<WorkoutSessionEntity>(
    _entities[2].properties[1],
  );

  /// See [WorkoutSessionEntity.dateTimestamp].
  static final dateTimestamp = obx.QueryIntegerProperty<WorkoutSessionEntity>(
    _entities[2].properties[2],
  );

  /// See [WorkoutSessionEntity.durationMinutes].
  static final durationMinutes = obx.QueryIntegerProperty<WorkoutSessionEntity>(
    _entities[2].properties[3],
  );

  /// See [WorkoutSessionEntity.exercisesJson].
  static final exercisesJson = obx.QueryStringProperty<WorkoutSessionEntity>(
    _entities[2].properties[4],
  );
}
